### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mycaravam** [Janusec/janusec#10]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)? ( at least Go 1.9 is required)  
go version go1.12 linux/amd64

### What version of PostgreSQL are you using (`psql --version`)? ( at least PostgreSQL 9.3 is required) 
psql (PostgreSQL) 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)

### Did you correctly configure the IP, Port, username, password, dbname of your PostgreSQL in ./config.json (Development) or /usr/local/janusec/config.json (Production), and verified OK by `psql -h 127.0.0.1 -U db_user -W janusec` ? 

That's working.
Janusec will not create the dbname for you.

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build631072740=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
Trying to start the server:
sudo ./janusec 

If possible, provide a test case for reproducing the error.

### What did you expect to see?
---

### What did you see instead?
2019/09/10 05:44:16 Janusec Application Gateway 0.9.4 Starting ...
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6f4a9e]

goroutine 23 [running]:
net/http.(*onceCloseListener).close(...)
	/usr/local/go/src/net/http/server.go:3286
sync.(*Once).Do(0xc000106100, 0xc0001d8d10)
	/usr/local/go/src/sync/once.go:44 +0xb3
net/http.(*onceCloseListener).Close(0xc0001060f0, 0xc0001fe001, 0x100000096ad1b)
	/usr/local/go/src/net/http/server.go:3282 +0x54
panic(0x8e3040, 0xdb0e10)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
net/http.(*onceCloseListener).Accept(0xc0001060f0, 0xc0000240a8, 0x8dacc0, 0xdb0d30, 0x959b60)
	<autogenerated>:1 +0x32
net/http.(*Server).Serve(0xc00020a000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2859 +0x22d
net/http.Serve(...)
	/usr/local/go/src/net/http/server.go:2456
main.main.func4(0xa1f5c0, 0xc000112da0)
	/home/user/go/src/github.com/Janusec/janusec/janusec.go:103 +0xf6
created by main.main
	/home/user/go/src/github.com/Janusec/janusec/janusec.go:101 +0x467

### Other information  
cat config.json 
{
	"node_role": "master",
	"master_node": {
		"admin_http_listen": ":9080",
		"admin_https_listen": ":9443",
		"database": {
			"host": "127.0.0.1",
			"port": "5432",
			"user": "janusec",
			"password": "123456",
			"dbname": "janusec"
		}
	},
	"slave_node": {
		"node_key": "",
		"sync_addr": "http://127.0.0.1:9080/janusec-api/"
	}
}

**Comment by ThiagoEscarrone** [comment]
are you using ubuntu0.18.04.1?
It's required CentOS/RHEL 7, or Debian 9, x86_64. I had this problem and was solved installing debian 9.3

**Comment by mycaravam** [comment]
I also tried it on 
`cat /proc/version`
Linux version 4.9.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23)
`cat /etc/issue`
Debian GNU/Linux 9 \n \l

And got the same error.
Any hint would be very welcome.

**Comment by zhyale** [comment]
The database need be created manually, and then refer to https://www.janusec.com/documentation/diagnose/
