### ISSUE TITLE
不支持同一域名下多个location吗？

### ISSUE THREAD

**Issue by uglylee** [Janusec/janusec#12]
Please answer these questions before submitting your issue. Thanks!

### Did you correctly configure the IP, Port, username, password, dbname of your PostgreSQL in ./config.json (Development) or /usr/local/janusec/config.json (Production), and verified OK by `psql -h 127.0.0.1 -U db_user -W janusec` ? 

Janusec will not create the dbname for you.

### What did you do?

If possible, provide a test case for reproducing the error.

**Comment by zhyale** [comment]
支持多个后端目标IP，可以添加Destination。
但暂不支持your_domain/abc、your_domain/xyz 使用不同的后端服务器。
