### ISSUE TITLE
能不能增加websocket代理支持

### ISSUE THREAD

**Issue by kenser** [Janusec/janusec#13]
RT，代理swoole和workman

**Comment by zhyale** [comment]
目前还不支持，后面会考虑增加，但暂无明确的时间表

**Comment by kenser** [comment]
好的，谢谢。期待 :D

**Comment by zhyale** [comment]
2019.12.17更新：已添加WebSocket功能，请测试体验。
注意事项：网关使用固定端口，因此客户端在连接的时候，域名后面不要带端口，ws默认80.
如下测试代码验证ok
server.go:
`package main

import (
    "flag"
    "log"
    "net/http"
    "time"

    "github.com/gorilla/websocket"
)

var addr = flag.String("addr", "localhost:8081", "http service address")

var upgrader = websocket.Upgrader{} // use default options

func echo(w http.ResponseWriter, r *http.Request) {
    c, err := upgrader.Upgrade(w, r, nil)
    if err != nil {
        log.Print("upgrade:", err)
        return
    }
    defer c.Close()
    for {
        message := time.Now().Format("2006-01-02 15:04:05")
        err = c.WriteMessage(websocket.TextMessage, []byte(message))
        if err != nil {
            log.Println("write:", err)
            break
        }
        time.Sleep(1*time.Second)
    }
}

func main() {
    flag.Parse()
    log.SetFlags(0)
    http.HandleFunc("/echo", echo)
    log.Fatal(http.ListenAndServe(*addr, nil))
}

`

client.go:
`package main

import (
    "flag"
    "log"
    "net/url"
    "os"
    "os/signal"
    "sync"

    "github.com/gorilla/websocket"
)

var addr = flag.String("addr", "websocket.your_domain.com", "http service address")
func main() {
    flag.Parse()
    log.SetFlags(0)

    interrupt := make(chan os.Signal, 1)
    signal.Notify(interrupt, os.Interrupt)

    u := url.URL{Scheme: "ws", Host: *addr, Path: "/echo"}
    log.Printf("connecting to %s", u.String())

    c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
    if err != nil {
        log.Fatal("dial:", err)
    }
    defer c.Close()

    done := make(chan struct{})
    wg := sync.WaitGroup{}
    wg.Add(1)

    go func() {
        defer close(done)
        for {
            _, message, err := c.ReadMessage()
            if err != nil {
                log.Println("read:", err)
                return
            }
            log.Printf("recv: %s", message)
        }
        wg.Done()
    }()

    wg.Wait()
}

`

**Comment by zhyale** [comment]
Test Swoole WebSocket Server OK with official websocket server demo code.

and , the client html code is as follow (change the domain name, without port number):

`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>WebSocket Client</title>
</head>
<body>
    <script type="text/javascript">
        var socket;
        if (window.WebSocket) {
            socket = new WebSocket("ws://your_domain.com/");
            socket.onmessage = function(event) {
                if(typeof(event.data)=="string"){
                    var ta = document.getElementById('responseText');
                    ta.value = ta.value +'\n'+ event.data
                }else{
                    var reader = new FileReader();  
                    reader.onload = function(event){
                                if(event.target.readyState == FileReader.DONE){
                                    var url = event.target.result;
                        }    
                        document.getElementById('responseText').src=url
                    }
                }
            };
            socket.onopen = function(event) {
                var ta = document.getElementById('responseText');
                ta.value = "contact start";
            };
            socket.onclose = function(event) {
                var ta = document.getElementById('responseText');
                ta.value = ta.value + "contact close";
            };
        } else {
            alert("browse not support WebSocket！");
        }

        function send(message) {
            if (socket.readyState == WebSocket.OPEN) {
                socket.send(message);
                var buffer = new ArrayBuffer(128);
                    socket.send(buffer);

                    var intview = new Uint32Array(buffer);
                    socket.send(intview);

                    var blob = new Blob([buffer]);
                    socket.send(blob);
            } else {
                alert("contact not start");
            }
        }
        function Close(){
            socket.close();
        }
    </script>
    <form onsubmit="return false;">
        <h3>My WebSocket Client</h3>
        <textarea id="responseText" style="width: 500px; height: 300px;"></textarea>
        <br> 
        <input type="text" name="message"  style="width: 300px" value="I am client">
        <input type="button" value="send" onclick="send(this.form.message.value)">
        <input type="button" value="close" onclick="Close()">
        <input type="button" onclick="javascript:document.getElementById('responseText').value=''" value="clear">
    </form>
    <br> 
    <br> 
</body>
</html>`
