### ISSUE TITLE
单nginx多server出现请求不同server，返回同一个server的资源

### ISSUE THREAD

**Issue by ydw1118** [Janusec/janusec#15]
```conf
# server-a.conf
server a {
    location / {
        root /path/a;
    }
}
```

```conf
#server-b.conf
server b {
    location / {
         root /path/b;
    }
}
```

访问b的时候response的都是a的资源

请问下，转发到后端是用路由配置里的ip:port还是域名配置里的域名？

**Comment by ydw1118** [comment]
> ```
> # server-a.conf
> server a {
>     location / {
>         root /path/a;
>     }
> }
> ```
> 
> ```
> #server-b.conf
> server b {
>     location / {
>          root /path/b;
>     }
> }
> ```
> 
> 访问b的时候response的都是a的资源
> 
> 请问下，转发到后端是用路由配置里的ip:port还是域名配置里的域名？

version：0.9.9

**Comment by ydw1118** [comment]
用了域名了，没问题了

**Comment by zhyale** [comment]
是的，需要使用域名访问。
访问后端的时候，网关会使用IP:Port去连后端，但在HTTP头部的Host字段中会带上域名。
