### ISSUE TITLE
应用配置不生效

### ISSUE THREAD

**Issue by webvul** [Janusec/janusec#18]
问题描述:
按照说明文档添加了SSL证书,然后在应用管理中去添加应用
请求路由:/edr/
路由类型:Reverse_Proxy
目标IP:port: 10.1.1.1:443
后端路径或绝对路径:/
域名配置
域名:test.nasg1212.net
证书:ACME自动证书
重定向到:https://10.1.1.1
浏览器去请求http://gw_ip/edr/ 直接返回404 not found,应该是路由没有生效,请教一下是哪里配置出现问题导致的?

**Comment by zhyale** [comment]
ACME自动证书只适用于公网域名可访问的场景，假域名无效；
测试时，先不要配置重定向以及二级目录；
还要注意scheme跟后端的端口号一致，后端用的443，则应该配置scheme为https 。
