### ISSUE TITLE
go build with error: local import "../backend" in non-local package

### ISSUE THREAD

**Issue by hsluoyz** [Janusec/janusec#2]
### What version of Go are you using (`go version`)? ( at least Go 1.9 is required)  

```
go version go1.10.3 windows/amd64
```

### What version of PostgreSQL are you using (`psql --version`)? ( at least PostgreSQL 9.3 is required) 

```
psql (PostgreSQL) 10.4
```

### Did you correctly configure the IP, Port, username, password, dbname of your PostgreSQL in ./config.json (Development) or /usr/local/janusec/config.json (Production), and verified OK by psql ? 

Yes

### Does this issue reproduce with the latest release?

Yes, with the ``master`` branch.

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yangluo\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoPath
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\yangluo\AppData\Local\Temp\go-build977797482=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

```
go get github.com/Janusec/janusec
cd janusec
go build
```

### What did you expect to see?

The project should be built correctly.

### What did you see instead?

```
C:\GoPath\src\github.com\Janusec\janusec>go build
frontend\api.go:19:2: local import "../backend" in non-local package
backend\application.go:15:2: local import "../data" in non-local package
backend\application.go:16:2: local import "../firewall" in non-local package
backend\application.go:17:2: local import "../models" in non-local package
frontend\api.go:21:2: local import "../settings" in non-local package
firewall\group_policy.go:22:2: local import "../usermgmt" in non-local package
backend\application.go:18:2: local import "../utils" in non-local package
```

### Other information  

This is because the project is using relative path in imports:

```go
import (
	"./backend"
	"./data"
	"./firewall"
	"./frontend"
	"./gateway"
	"./settings"
	"./utils"
)
```

They should be replaced with absolute path:

```go
import (
	"github.com/Janusec/janusec/backend"
	"github.com/Janusec/janusec/data"
	"github.com/Janusec/janusec/firewall"
	"github.com/Janusec/janusec/frontend"
	"github.com/Janusec/janusec/gateway"
	"github.com/Janusec/janusec/settings"
	"github.com/Janusec/janusec/utils"
)

```

The absolute import path is the **standard`` way to import libraries in Go. So I think we should fix it.

**Comment by Janusec** [comment]
Hi, @hsluoyz  , now the source code and release script are suitable for Linux, CentOS 7 is prefered.
The build instruct should be:
go build janusec.go
not “go build" .
We will also update it fow Windows developers.

**Comment by hsluoyz** [comment]
Thanks. It works now.
