### ISSUE TITLE
CSS error after many F5

### ISSUE THREAD

**Issue by vhostvn** [Janusec/janusec#25]
Hi,

we get this file error after many F5 in browser: https://congpro.biz/swiper.min.css

can you help?

first time load:
![Uploading 76FDA05A-580A-40FD-B14C-44D7EE4188B3.png…]()

After F5:
![Uploading C5582C50-ECFF-4F37-AA5D-6908DCD897BE.jpeg…]()

**Comment by zhyale** [comment]
Try to clean cache files under /usr/local/janusec/static/cdncache/ and try again, check if it occurs again.

**Comment by vhostvn** [comment]
Yes, i already delete and these files is still error when using behind Janusec.

If we use hosts file point direct to origin server. No error happened.

**Comment by vhostvn** [comment]
Our partner replied:

> When directly access to origin server, there is no issue at all.
> But when through Janusec server, there is an issue. We are not familiar with your Janusec server, but most likely some issue on your Janusec server end. The issue is about static file compression, could be your Janusec server is lack of compression support, such "br" compression support. You many need to ask your Janusec support to check more details.

**Comment by zhyale** [comment]
We add brotli decompress now but have not try it yet. 
Please try it : https://www.janusec.com/download/janusec-1.2.4-amd64.tar.gz

**Comment by vhostvn** [comment]
Hi,

Did this patch fix error on issue: https://github.com/Janusec/janusec/issues/19 ?

**Comment by zhyale** [comment]
> Hi,
> 
> Did this patch fix error on issue: #19 ?

Yes, include that fix.

**Comment by zhyale** [comment]
Version 1.2.5 can enable or disable cache static files, include all previous fix.
https://www.janusec.com/download/janusec-1.2.5-amd64.tar.gz

**Comment by vhostvn** [comment]
Thanks for your update
