### ISSUE TITLE
该应用是不能在mac上开发运行吗？build报错了

### ISSUE THREAD

**Issue by zhaoxianhua** [Janusec/janusec#27]
➜  janusec git:(master) ✗ go build                                                  
# github.com/google/nftables/expr
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/byteorder.go:28:30: undefined: unix.NFT_BYTEORDER_NTOH
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/byteorder.go:29:30: undefined: unix.NFT_BYTEORDER_HTON
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:31:26: undefined: unix.NFT_CT_STATE
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:32:26: undefined: unix.NFT_CT_DIRECTION
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:33:26: undefined: unix.NFT_CT_STATUS
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:34:26: undefined: unix.NFT_CT_MARK
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:35:26: undefined: unix.NFT_CT_SECMARK
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:36:26: undefined: unix.NFT_CT_EXPIRATION
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:37:26: undefined: unix.NFT_CT_HELPER
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:38:26: undefined: unix.NFT_CT_L3PROTOCOL
../../pkg/mod/github.com/google/nftables@v0.0.0-20210514154851-a285acebcad3/expr/ct.go:38:26: too many errors

**Comment by zhyale** [comment]
Linux OS is required for production environment, please use:
`CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build janusec.go`

or build under Linux.
