### ISSUE TITLE
Issues: CAPTCHA & HSTS 

### ISSUE THREAD

**Issue by Trihoang040399** [Janusec/janusec#28]
I using version 1.2.6

I have 2 questions:
1/ Enable action=CAPTCHA in CC policy 

![IssueCaptcha](https://user-images.githubusercontent.com/63949824/136204186-f8ed317e-bd27-47e3-8e63-b23c954348af.PNG)

It shows captcha but when i input the right captcha, it shows {"statusCode":404, "error":"Not Found","message":"Not Found"}
![IssueCaptcha2](https://user-images.githubusercontent.com/63949824/136204213-adc8b9b4-649a-40d5-82bf-54158221f10f.PNG)

Why does it show that I can not access the website?

2/ Enable HSTS
I check the response headers, it has strict-transport-security.
![IssueHSTS](https://user-images.githubusercontent.com/63949824/136204269-49cc3247-4a22-451d-8289-76d349daadc4.PNG)

But when I access the website by HTTP, it is still accessible. Can you explain how it works?

Thanks!

**Comment by zhyale** [comment]
Thank you, this is a bug, and now it is fixed in v1.2.6fix1.
Now you can re-download it from https://github.com/Janusec/janusec/releases  or https://doc.janusec.com/
