### ISSUE TITLE
Admin Listen HTTPS error

### ISSUE THREAD

**Issue by m8522s** [Janusec/janusec#33]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)? ( at least Go 1.9 is required)  
go version go1.16.7 linux/amd64

### What version of PostgreSQL are you using (`psql --version`)? ( at least PostgreSQL 9.3 is required) 
psql (PostgreSQL) 10.17

### Did you correctly configure the IP, Port, username, password, dbname of your PostgreSQL in ./config.json (Development) or /usr/local/janusec/config.json (Production), and verified OK by `psql -h 127.0.0.1 -U db_user -W janusec` ? 
Yes

### Does this issue reproduce with the latest release?
Yes, v1.2.6fix1

### What operating system and processor architecture are you using (`go env`)?
Red Hat Enterprise Linux release 8.5 (Ootpa)
Linux 4.18.0-348.el8.x86_64 x86_64

### What did you do?
Access web URL at https://ipaddress:9443/janusec-admin/

### What did you expect to see?
The login web page

### What did you see instead?
Firefox reports:
```
Secure Connection Failed
An error occurred during a connection to 35.158.100.227:9443. Peer reports it experienced an internal error.
Error code: SSL_ERROR_INTERNAL_ERROR_ALERT
```

### Other information  
Janusec logs:
```
2021/11/10 08:45:55 http: TLS handshake error from 178.202.X.Y:49853: Unknown Host:
```
- The login over insecure http://ipaddress:9080/janusec-admin/ is working fine.
- Same result with SELINUX disabled/enabled
- Local time and date are accurate

**Comment by zhyale** [comment]
Do not use IP address with https, you can use one domain name of your domains in Application Management.

**Comment by m8522s** [comment]
The same happens, when I use the domain name:
https://ec2-35-158-130-118.eu-central-1.compute.amazonaws.com:9443/janusec-admin

Even the log message is the same:
```
Nov 11 15:29:50 ip-172-31-0-201.eu-central-1.compute.internal janusec[17972]: 2021/11/11 15:29:50 http: TLS handshake error from 178.202.X.Y:57812: Unknown Host: ec2-35-158-130-118.eu-central-1.compute.amazonaws.com
```
Any idea?

**Comment by zhyale** [comment]
> The same happens, when I use the domain name: https://ec2-35-158-130-118.eu-central-1.compute.amazonaws.com:9443/janusec-admin
> 
> Even the log message is the same:
> 
> ```
> Nov 11 15:29:50 ip-172-31-0-201.eu-central-1.compute.internal janusec[17972]: 2021/11/11 15:29:50 http: TLS handshake error from 178.202.X.Y:57812: Unknown Host: ec2-35-158-130-118.eu-central-1.compute.amazonaws.com
> ```
> 
> Any idea?

Please use the short domain name, which client users used.

**Comment by m8522s** [comment]
Same result. I tried with a short FQDN but receive the exact same error message:
```
Nov 12 13:12:51 ip-172-31-14-132.eu-central-1.compute.internal janusec[18040]: 2021/11/12 13:12:51 http: TLS handshake error from 178.202.X.Y:48172: Unknown Host: www.mydomain.com
```
I also set the same hostname in `config.json` inside the Janusec directory.

Where do I need to define that host, so that isn't unknow to Janusec any more?

**Comment by zhyale** [comment]
The domain you used must be configured in one Application, and a certificate must be configured for it. If it continues to be error, please paste the Application screenshot under Application Management.

**Comment by m8522s** [comment]
How can I securely configure an application if I can't reach the admin page first?
Plain http is not an option as I access the Janusec server over the Internet.

**Comment by zhyale** [comment]
The first application configuration with a domain is required before https is available.
You can not use https without them.
