### ISSUE TITLE
会添加缓存功能吗？

### ISSUE THREAD

**Issue by m1911** [Janusec/janusec#4]
作者会考虑添加nginx 那样的缓存功能吗？

**Comment by Janusec** [comment]
会的，后续版本会加入基本的静态文件缓存机制。

**Comment by m1911** [comment]
@Janusec 操作界面没有做中文的？

**Comment by Janusec** [comment]
@m1911  janusec-latest.tar.gz 文件为已打包好的安装文件，可直接安装，不需要go环境，不需要重新编译。 为便于更新维护，只提供英文界面，如果不太习惯可参照中文的指引 https://www.janusec.com/cn/ 。
