### ISSUE TITLE
忘记双因子认证如何临时关闭此功能

### ISSUE THREAD

**Issue by gengwanwan** [Janusec/janusec#41]

**Comment by zhyale** [comment]
可在 全局设置 菜单里面关闭

**Comment by gengwanwan** [comment]
问题是，我现在无法登录到后台管理web，我可以从修改数据库里面关闭嘛？

**Comment by zhyale** [comment]
> 问题是，我现在无法登录到后台管理web，我可以从修改数据库里面关闭嘛？

在settings 表，有一行是  authenticator_enabled，将true改为 false ，重启服务。
