### ISSUE TITLE
统一身份认证用户的权限有问题

### ISSUE THREAD

**Issue by cnwelee** [Janusec/janusec#47]
我们尝试启用飞书和LDAP登录，启用都成功了，而且可以用相应账户登录到系统。但是目前问题是给飞书或者LDAP用户配置更高权限遇到问题，比如给某个LDAP用户配置了证书管理员（可管理所有证书内容）、应用管理员（可管理所有应用）甚至超级管理员（授予/撤销用户权限，管理WAF/CC规则），但是这个用户仍然看不到之前已创建的应用（只有手动把这个用户设置成某个应用的负责人才能看到）

**Comment by zhyale** [comment]
Thank you for your feedback, this was a bug and has been fixed by v1.4.0fix7:  https://github.com/Janusec/janusec/releases

**Comment by cnwelee** [comment]
赞，确实已经修复了
