### ISSUE TITLE
你好一直在关注janusec应用网关，感觉非常好用。 希望更新一下oauth2中的钉钉验证版本，最新版本可以识别到钉钉应用点击立即登录。

### ISSUE THREAD

**Issue by nihao364097872** [Janusec/janusec#52]
你好一直在关注janusec应用网关，感觉非常好用。
希望更新一下oauth2中的钉钉验证版本，最新版本可以识别到钉钉应用点击立即登录。

**Comment by janusec2** [comment]
Requirement received, please waiting the future release, and the updation information will be synchronised here.

**Comment by janusec2** [comment]
Hi, 
The v1.5.0 version has upgrade to the new Dingtalk OAuth2 SDK, available at https://github.com/Janusec/janusec/releases

**Comment by nihao364097872** [comment]
你好，经过使用此版本非常好用。
有一个问题，如何添加多个域名？
举例我有多个域名
aaa.abc.com
bbb.abc.com
这里只能添加一个回调地址，比如这里写的aaa.abc.com，bbb开启认证扫码后就会跳转到aaa.abc.com的系统，应该如何解决




恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Janusec/janusec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月24日(星期天) 中午1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Janusec/janusec] 你好一直在关注janusec应用网关，感觉非常好用。 希望更新一下oauth2中的钉钉验证版本，最新版本可以识别到钉钉应用点击立即登录。 (Issue #52)





 
Hi,
 The v1.5.0 version has upgrade to the new Dingtalk OAuth2 SDK, available at https://github.com/Janusec/janusec/releases

**Comment by janusec2** [comment]
钉钉回调地址那里不用添加多域名，应用本身可以在应用管理那里添加多域名，经测试使用新增的域名未发现异常。

**Comment by nihao364097872** [comment]
谢谢，已解决，回调哪里写错了，使用没问题很棒。



恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Janusec/janusec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Janusec/janusec] 你好一直在关注janusec应用网关，感觉非常好用。 希望更新一下oauth2中的钉钉验证版本，最新版本可以识别到钉钉应用点击立即登录。 (Issue #52)





 
钉钉回调地址那里不用添加多域名，应用本身可以在应用管理那里添加多域名，经测试使用新增的域名未发现异常。
