### ISSUE TITLE
请问有计划在未来版本中加入负载均衡代理到多个节点吗

### ISSUE THREAD

**Issue by KafuuEriri** [Janusec/janusec#54]

**Comment by janusec2** [comment]
The GSLB function was already finished, you can get it from the releases: https://github.com/Janusec/janusec/releases 
Note: 
1. The releases with suffix -pro.tar.gz are professional edition (close source). 
2. Guide for GSLB is avalable at https://janusec.github.io/documentation/appendix-gslb/
