### ISSUE TITLE
请问SDL SaaS还有在做吗？

### ISSUE THREAD

**Issue by guxianhua** [Janusec/janusec#9]
我发现了https://jingyan.baidu.com/album/ac6a9a5e1b14562b653eac35.html，但是saas.janusec.com已经无法访问。如果不做这个业务了，SDL SaaS可以开源吗？谢谢！！
持续关注你们！

**Comment by zhyale** [comment]
你好，SDL SaaS已下线，不过代码已经开源在 https://github.com/zhyale/SDL-SaaS ，仅供参考，已无法提供支持了。
